name: Shopify live change

on:
  push:
    branches:
      - main

jobs:
  create_live_change:
    runs-on: ubuntu-latest

    steps:
    - name: Check for shopify bot
      if: contains(github.event.head_commit.message, 'shopify[bot]')
      run: echo "shopify bot detected"
    - name: Create live-change branch
      run: |
        git checkout -b live-change-$(date +%s)
        git push -u origin live-change-$(date +%s)
    - name: Create pull request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Live change"
        head: live-change-$(date +%s)
        base: develop
