name: Main to Develop PR

on:
  push:
    branches:
      - main
    paths:
      - '**'
    tags:
      - '**'
    author:
      - shopify[bot]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Sync Changes from Main to Develop"
        head: main
        base: develop
        labels: "sync"
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
