name: Check for Shopify bot changes

on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
    - name: Configure Git user email
      run: git config --global user.email "you@example.com"
    - name: Configure Git user name
      run: git config --global user.name "Your Name"
    - name: Get latest commits
      run: git fetch --all
    - name: Check commit message of last push
      run: |
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        if [ "$LAST_COMMIT_MESSAGE" == "Update from Shopify for theme shopify-test/main" ]; then
          current_time=$(date "+%Y.%m.%d-%H.%M.%S")
          random_number=$(shuf -i 1-1000 -n 1)
          new_branch_name="live-change-$current_time-$random_number"
          git branch $new_branch_name
          git push --set-upstream origin $new_branch_name
          git checkout $new_branch_name
        else
          echo "The last push was not made by shopify[bot], the action will stop running"
        fi
    - name: Get latest commits after new branch
      run: git fetch --all
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Update from Shopify for theme shopify-test/main"
        branch: $new_branch_name
        base: develop
        token: ${{ secrets.TOKEN }}
